---

- name: php-fpm backend servers
  hosts: php_fpm
  become: yes
  roles:
    - php

- name: nginx frontend servers
  hosts: nginx
  become: yes
  roles:
    - http

- name: test frontend localhost server
  hosts: localhost
  roles:
    - test
